# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [2]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os


# Import API key
g_key = os.environ.get('GKEY')

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [3]:
# Load the csv into a dataframe
city_weather_data_df = pd.read_csv("../output_data/city_weather_data.csv", encoding="utf-8")
city_weather_data_df

,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Date
0,Hermanus,ZA,-34.42,19.23,52.00,95.0,58.0,5.91,1.602987e+09
1,Kruisfontein,ZA,-34.00,24.73,55.99,95.0,100.0,11.95,1.602987e+09
2,Butaritari,KI,3.07,172.79,82.51,77.0,23.0,20.36,1.602987e+09
3,Kodiak,US,57.79,-152.41,46.40,65.0,90.0,5.82,1.602988e+09
4,Hobart,AU,-42.88,147.33,61.00,54.0,75.0,6.93,1.602987e+09
...,...,...,...,...,...,...,...,...,...
560,Kavieng,PG,-2.57,150.80,84.25,74.0,10.0,7.61,1.602988e+09
561,Tabory,RU,58.52,64.55,29.07,96.0,0.0,9.75,1.602988e+09
562,Port-Gentil,GA,-0.72,8.78,77.74,86.0,100.0,9.75,1.602988e+09
563,Petropavlovsk-Kamchatskiy,RU,53.05,158.65,44.60,69.0,75.0,4.47,1.602988e+09
564,Saint-Pierre,PM,46.77,-56.17,51.80,100.0,90.0,17.22,1.602988e+09

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [5]:
# Configure gmaps with API key
gmaps.configure(api_key=g_key)

In [6]:
# Store 'Lat' and 'Lng' into  locations 
locations = city_weather_data_df[["Lat", "Lng"]].astype(float)

# Convert Humidity to float and store
humidity_prcnt = city_weather_data_df["Humidity"].astype(float)

In [8]:
# Create a Humidity Heatmap layer
fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=humidity_prcnt, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 1)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

### My weather criteria:
- A temperature >= 70 but <= 80
- A wind speed less <= to 10 mph
- Cloudiness below 10%

In [11]:
hotel_df = city_weather_data_df[(city_weather_data_df['Max Temp'] >= 70) & (city_weather_data_df['Max Temp'] <=80 ) & (city_weather_data_df['Wind Speed'] <=10 ) & (city_weather_data_df['Cloudiness'] <10 )]
hotel_df

,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Date
29,Busselton,AU,-33.65,115.33,73.99,36.0,0.0,8.05,1.602987e+09
105,Sehithwa,BW,-20.47,22.72,70.21,27.0,0.0,7.92,1.602987e+09
144,Los Negros,BO,-17.73,-63.43,78.80,69.0,0.0,5.82,1.602987e+09
146,Siguiri,GN,11.67,-9.50,76.60,66.0,0.0,2.64,1.602987e+09
157,Carlsbad,US,33.16,-117.35,70.00,94.0,1.0,5.82,1.602987e+09
197,Mecca,SA,21.43,39.83,77.67,16.0,0.0,5.93,1.602987e+09
208,Mwense,ZM,-10.38,28.70,73.24,49.0,0.0,7.61,1.602987e+09
276,Sabinas Hidalgo,MX,26.50,-100.17,72.03,60.0,0.0,5.39,1.602987e+09
352,Pokhara,NP,28.23,83.98,74.16,52.0,0.0,0.72,1.602987e+09
359,Constitucion,MX,23.99,-104.67,73.40,23.0,5.0,4.65,1.602987e+09
468,Kang,BW,-23.68,22.79,72.48,25.0,0.0,8.90,1.602987e+09
485,Sarwar,IN,26.07,75.00,79.66,44.0,0.0,6.02,1.602987e+09
520,Vega De Alatorre,MX,20.03,-96.63,75.47,84.0,2.0,7.96,1.602988e+09
523,Nova Esperanca,BR,4.44,-61.12,73.38,65.0,4.0,2.71,1.602988e+09
538,Salalah,OM,17.02,54.09,73.40,43.0,0.0,5.82,1.602988e+09

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [13]:
hotel_df['Hotel Name'] = ""
hotel_df

<ipython-input-13-cb2d5672db59>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hotel_df['Hotel Name'] = ""

,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Date,Hotel Name
29,Busselton,AU,-33.65,115.33,73.99,36.0,0.0,8.05,1.602987e+09,
105,Sehithwa,BW,-20.47,22.72,70.21,27.0,0.0,7.92,1.602987e+09,
144,Los Negros,BO,-17.73,-63.43,78.80,69.0,0.0,5.82,1.602987e+09,
146,Siguiri,GN,11.67,-9.50,76.60,66.0,0.0,2.64,1.602987e+09,
157,Carlsbad,US,33.16,-117.35,70.00,94.0,1.0,5.82,1.602987e+09,
197,Mecca,SA,21.43,39.83,77.67,16.0,0.0,5.93,1.602987e+09,
208,Mwense,ZM,-10.38,28.70,73.24,49.0,0.0,7.61,1.602987e+09,
276,Sabinas Hidalgo,MX,26.50,-100.17,72.03,60.0,0.0,5.39,1.602987e+09,
352,Pokhara,NP,28.23,83.98,74.16,52.0,0.0,0.72,1.602987e+09,
359,Constitucion,MX,23.99,-104.67,73.40,23.0,5.0,4.65,1.602987e+09,
468,Kang,BW,-23.68,22.79,72.48,25.0,0.0,8.90,1.602987e+09,
485,Sarwar,IN,26.07,75.00,79.66,44.0,0.0,6.02,1.602987e+09,
520,Vega De Alatorre,MX,20.03,-96.63,75.47,84.0,2.0,7.96,1.602988e+09,
523,Nova Esperanca,BR,4.44,-61.12,73.38,65.0,4.0,2.71,1.602988e+09,
538,Salalah,OM,17.02,54.09,73.40,43.0,0.0,5.82,1.602988e+09,

In [15]:
# Params dictionary to update each iteration
params = {
    "radius": 5000,
    "types": "lodging",
    "keyword": "hotel",
    "key": g_key
}

# Use the lat/lng we recovered to identify airports
for index, row in hotel_df.iterrows():
    # Get lat, lng from df
    lat = row["Lat"]
    lng = row["Lng"]

    # Change location each iteration while leaving original params in place
    params["location"] = f"{lat},{lng}"

    # Use the search term: "International Airport" and our lat/lng
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # Make request and print url
    hotel_name = requests.get(base_url, params=params)
    
    # Convert to json
    hotel_name = hotel_name.json()

    # Try-except to skip any that are missing data.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotel_name["results"][0]["name"]
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")

/Users/seanistre/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

Missing field/result... skipping.
Missing field/result... skipping.

In [17]:
# Remove the cities without a hotel
hotel_df = hotel_df[~(hotel_df["Hotel Name"] == "")]
hotel_df

,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Date,Hotel Name
29,Busselton,AU,-33.65,115.33,73.99,36.0,0.0,8.05,1.602987e+09,Esplanade Hotel
105,Sehithwa,BW,-20.47,22.72,70.21,27.0,0.0,7.92,1.602987e+09,MONLEK GUEST HOUSE
157,Carlsbad,US,33.16,-117.35,70.00,94.0,1.0,5.82,1.602987e+09,Carlsbad Inn Beach Resort
197,Mecca,SA,21.43,39.83,77.67,16.0,0.0,5.93,1.602987e+09,AL kISWAH Towers Hotel
208,Mwense,ZM,-10.38,28.70,73.24,49.0,0.0,7.61,1.602987e+09,GrandPalm Lodge
276,Sabinas Hidalgo,MX,26.50,-100.17,72.03,60.0,0.0,5.39,1.602987e+09,Hotel El Rancho
352,Pokhara,NP,28.23,83.98,74.16,52.0,0.0,0.72,1.602987e+09,Hotel Rani Mahal
359,Constitucion,MX,23.99,-104.67,73.40,23.0,5.0,4.65,1.602987e+09,Hotel Gobernador
468,Kang,BW,-23.68,22.79,72.48,25.0,0.0,8.90,1.602987e+09,"Phofu Kalahari Lodge - Kang, Botswana"
485,Sarwar,IN,26.07,75.00,79.66,44.0,0.0,6.02,1.602987e+09,Hotel Tak Palace
520,Vega De Alatorre,MX,20.03,-96.63,75.47,84.0,2.0,7.96,1.602988e+09,Hotel Dorado
523,Nova Esperanca,BR,4.44,-61.12,73.38,65.0,4.0,2.71,1.602988e+09,Hotel AmazÃ´nia
538,Salalah,OM,17.02,54.09,73.40,43.0,0.0,5.82,1.602988e+09,Al Jabal

In [18]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [20]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(markers)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))